### ISSUE TITLE
Roadmap OnTheGo

### ISSUE THREAD

**Issue by acedward** [Moblox/onthego-tickets#6]
## Prioridades 1
- [ ] modificaciones y soporte a VSPT
- [ ] modificaciones y soporte a UDP
- [ ] modificaciones y soporte a SKBERGE
- [ ] modificaciones y soporte a BANCO CHILE
- [ ] eval. desempeño/competencias

## Prioridades 2
- [ ] portal noticias
- [ ] beneficios
- [ ] infraestructura posibles clientes
- [ ] lms
- [ ] infraestructura cloud (saas)

## Prioridades 3
- [ ] eval. objetivos / plan de acción
- [ ] aplicación Android
- [ ] aplicación iPhone
- [ ] chat / im

## Prioridades 4
- [ ] call center
- [ ] asistencia
- [ ] reclutamiento
- [ ] dashboard
- [ ] gestion del talento

**Comment by mundurragacl** [comment]
https://fast.wistia.net/embed/iframe/2pavwkdpv9?popover=true

un modulo de premios... o reconocimientos....para que aparezca en la parte de news...

**Comment by mundurragacl** [comment]
https://fast.wistia.net/embed/iframe/fpr5lgdjpq?popover=true 
https://fast.wistia.net/embed/iframe/1u2izikfg2?popover=true
https://fast.wistia.net/embed/iframe/px0m6sdqvj?popover=true
https://fast.wistia.net/embed/iframe/d9sljopepx?popover=true

un con http://aylien.com/text-api-demo text analisys for sentimental analisis de la empresa o un modulo de engament para ver cuanto usan la pagina y uso o comentarios por usuario local empresa

**Comment by mundurragacl** [comment]
https://www.youtube.com/watch?v=6imAxQtyFeU&feature=youtu.be 

mobile app idea....
